controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "MPPIController"
      vx_max: 0.1
      vx_min: -0.4
local_costmap:
  ros__parameters:
    resolution: 0.05
    robot_radius: 0.33
    plugins: ["obstacle_layer", "denoise_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
    denoise_layer:
      plugin: "custom_plugins::DenoiseLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.66  # 2 * robot_radius

